### PR TITLE
Fixing issues 47, 49, 53  and 55

### PR DESCRIPTION
**Pull request by luismalddonado**
Fixing issues 47, 49, 53 and 55

### CODE REVIEW

**Comment by CV8R** [comment]
Hi @luismalddonado I have been working on this too and looks like we need some additional changes for the actions.  I am learning how to use GitHub and not show how to to a Pull Request on the v2.0.0 release.  I will share what I have done to assist if you can import the changes.

I also made some other small mods that we can work in.

**Comment by CV8R** [comment]
I pushed a commit to my fork, its a bit of a mess the way I have done it.  I am not a dev and learning how to use Github.  The changes I made are commented with # CHANGED.

**Comment by CV8R** [comment]
Should add a breaking changes note to the readme since these changes are likely to mean changes to references Automations.

**Comment by jnimmo** [comment]
Thanks both, just checking this includes what you were working on too @CV8R ?
@luismalddonado Could you please change into the component directory and run '''black .''' to tidy up the formatting then I can merge it.

**Comment by luismalddonado** [comment]
> Thanks both, just checking this includes what you were working on too @CV8R ? @luismalddonado Could you please change into the component directory and run '''black .''' to tidy up the formatting then I can merge it.

Done! Sorry. I have 0 experience with phyton.

**Comment by CV8R** [comment]
Will review and add if needed later today.

**Comment by luismalddonado** [comment]
> Will review and add if needed later today.

Anyway when I have time and get used to homeassitant and pyton I will review all the code and try to make things in a better way. Now it is just working! At least for me.

**Comment by CV8R** [comment]
With my lack of GiHub experience I am struggling to follow the changes and the files I pull down with GiHub desktop appear earlier than the v2.0.0 release.  I have been editing them on my system direct...

Note, without adding the following to climate.py the new climate feature lags are not being used and its defaulting to the legacy off mode.  Once added, it is likely to break Automations (it did on mine) but easy to fix - we should add a breaking change warning once set to false.

```
_enable_turn_on_off_backwards_compatibility = False

```
As per:
[https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/](url)

Otherwise. Best go ahead and then I will try again later once the changes are merged.

I found some other things like CHN MODE and ONOFF being sent out of order, but will try add those later after these changes.

**Comment by luismalddonado** [comment]
What is  the status @jnimmo ??? I have this code working since 7 days is far more stable than "main" branch.  Current "main" branch is simply not working

**Comment by jnimmo** [comment]
Please ensure to install the pre-commit hooks in future to ensure it passes linting as I can't modify your pull request to fix it -

pip3 install pre-commit
pre-commit install
pre-commit run --all-files

**Pull request merged**
